
services:
  api:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prd
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL  # URL de conexão
      - SPRING_DATASOURCE_USERNAME=RM552218  # Usuário padrão
      - SPRING_DATASOURCE_PASSWORD=120904  # Senha
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=oracle.jdbc.OracleDriver  # Driver JDBC
