CREATE TABLE tb_caminhao (
                          id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                          placa VARCHAR2(7) UNIQUE NOT NULL,
                          capacidade NUMBER NOT NULL,
                          motorista VARCHAR2(100)
);
CREATE TABLE tb_rota (
                         id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                         descricao VARCHAR2(100),
                         distancia_km NUMBER
);


CREATE TABLE tb_coleta (
                           id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                           hora TIMESTAMP NOT NULL,
                           caminhao_id NUMBER,
                           rota_id NUMBER,
                           FOREIGN KEY (id) REFERENCES tb_caminhao(id),
                           FOREIGN KEY (id) REFERENCES tb_rota(id)
);



CREATE TABLE tb_morador (
                            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                            nome VARCHAR2(50) NOT NULL,
                            endereco VARCHAR2(100) NOT NULL,
                            telefone NUMBER(11),
                            email VARCHAR2(50) UNIQUE NOT NULL
);


CREATE TABLE TB_USERS (
                          ID NUMBER PRIMARY KEY,
                          USERNAME VARCHAR2(50) NOT NULL,
                          PASSWORD VARCHAR2(50) NOT NULL,
                          ROLE VARCHAR2(50) DEFAULT 'USER'
);


